---
# tasks file for db
- name: Show info about the env this host belongs to
  debug: msg="This host is in {{ env }} environment!!!"

#- name: "DEBUG HOSTVARS"
#  debug: "{{ ansible_ens4.ipv4.address }}"
  # debug: msg=ansible_default_ipv4.address
  # debug: msg="{{ hostvars }}"
  #debug: msg="{{ lookup('dig', ansible_host) }}"
  # debug: msg="{{ ansible_hostname }}"
  # command: "ip a | grep "global ens4" | awk '{ print $2 }' | sed 's/\/32//'"
  # register: result
# - set_fact:
# - debug: var=result.stdout_lines
  #debug: msg="{{ hostvars['db']['ansible_default_ipv4']['address'] }}"


- name: Change mongo config file
  template:
    src: mongod.conf.j2 # <-- Путь до локального файла-шаблона
    dest: /etc/mongod.conf # <-- Путь на удаленном хосте
    mode: 0644 # <-- Права на файл, которые нужно установить
  notify: restart mongod



