---
- name: Configure MongoDB host # <-- Словесное описание сценария (name)
  hosts: db # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  become: true # <-- Выполнить задание от root       
  gather_facts: no

  roles:
    - db
