---
# Установим в цикле все зависимости
- name: Install ruby and rubygems and required packages
  apt: 
    update_cache: yes
    name: ['ruby-full', 'ruby-bundler', 'build-essential']
    state: present